server:
  port: 8083

spring:
  application:
    name: ms-suppliers
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres-suppliers:5432/suppliers
    username: postgres
    password: "1234" # Es mejor ponerlo entre comillas por si acaso
    driver-class-name: org.postgresql.Driver

  # IMPORTANTE: kafka debe estar alineado con datasource
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Esta parte es VITAL para que veas el error en la consola de ms-suppliers
logging:
  level:
    root: INFO
    uptc.edu.co: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

gateway:
  secret: ${GATEWAY_SECRET:shared-super-secret}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka/}