spring:
  application:
    name: ms-auth
  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8081}

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET_BASE64:c3VwZXItc2VjcmV0LWtleS1mb3Itand0LW11c3QtYmUtMzItYnl0ZXMtbWluaW11bQ==}
  expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}